apiVersion: apps/v1
kind: Deployment
metadata:
  name: contract-analyzer-analysis-ms-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contract-analyzer-analysis-ms
  template:
    metadata:
      labels:
        app: contract-analyzer-analysis-ms
    spec:
      containers:
        - name: contract-analyzer-analysis-ms-c
          image: bchaparro4/contract-analyzer-analysis-ms:${MS_1_VERSION}
          ports:
            - containerPort: 8000