apiVersion: v1
kind: Service
metadata:
  name: contract-analyzer-analysis-ms-service
spec:
  selector:
    app: contract-analyzer-analysis-ms
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000